import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ryan' at '6/18/16 5:26 PM' with Gradle 2.9
 *
 * @author ryan, @date 6/18/16 5:26 PM
 */
public class LibraryTest {
    /*@Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
