package com.github.rye761.unsplash;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ryan' at '6/18/16 5:26 PM' with Gradle 2.9
 *
 * @author ryan, @date 6/18/16 5:26 PM
 */
public class Library {
    public void print(String value) {
    	System.out.println(value);
    }
}
